"""Agent reliability and replay lab."""
from alembic import op
import sqlalchemy as sa
revision="0004";down_revision="0003";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("agent_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id"),nullable=False,index=True),sa.Column("project_id",sa.String(36),sa.ForeignKey("projects.id"),nullable=False,index=True),sa.Column("environment_id",sa.String(36),sa.ForeignKey("environments.id"),nullable=False,index=True),sa.Column("name",sa.String(200),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("findings_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("agent_steps",sa.Column("id",sa.String(36),primary_key=True),sa.Column("agent_run_id",sa.String(36),sa.ForeignKey("agent_runs.id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("position",sa.Integer(),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("status",sa.String(30),nullable=False))
    op.create_table("tool_calls",sa.Column("id",sa.String(36),primary_key=True),sa.Column("agent_step_id",sa.String(36),sa.ForeignKey("agent_steps.id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("tool",sa.String(200),nullable=False),sa.Column("arguments_json",sa.JSON(),nullable=False),sa.Column("result_json",sa.JSON()),sa.Column("status",sa.String(30),nullable=False),sa.Column("confirmed",sa.Boolean(),nullable=False),sa.Column("latency_ms",sa.Integer()))
    op.create_table("replay_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("project_id",sa.String(36),sa.ForeignKey("projects.id"),nullable=False,index=True),sa.Column("request_id",sa.String(36),sa.ForeignKey("requests.id"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("configuration_json",sa.JSON(),nullable=False),sa.Column("error",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)))
    op.create_table("replay_candidates",sa.Column("id",sa.String(36),primary_key=True),sa.Column("replay_run_id",sa.String(36),sa.ForeignKey("replay_runs.id",ondelete="CASCADE"),nullable=False,index=True),sa.Column("provider",sa.String(80),nullable=False),sa.Column("model",sa.String(120),nullable=False),sa.Column("response",sa.Text(),nullable=False),sa.Column("reliability",sa.Integer(),nullable=False),sa.Column("latency_ms",sa.Integer(),nullable=False),sa.Column("estimated_cost",sa.Float()),sa.Column("is_demo",sa.Boolean(),nullable=False),sa.Column("detector_results_json",sa.JSON(),nullable=False))
def downgrade():
    for table in ["replay_candidates","replay_runs","tool_calls","agent_steps","agent_runs"]:op.drop_table(table)
