/** Kampanya 3 — ZAMAN BÜKÜCÜ. Tahmin, planlama, öngörü. */
import type { QuestInput } from "@/domain/content-types";
import { SAFE } from "./safety-notes";

const base = {
  version: 1,
  campaignId: "time-bender",
  npcId: "clockmaker",
  requiresPurchase: false as const,
};

const safetyBase = {
  requiresPurchase: false as const,
  contactsStrangers: false as const,
  photographsPeople: false as const,
  sharesLocation: false as const,
};

const OVER = (a: string, b: string) => ({ compare: { a, op: "gt" as const, b, ratio: 1.15 } });
const UNDER = (a: string, b: string) => ({ compare: { a, op: "lt" as const, b, ratio: 0.85 } });

export const TIME_BENDER_QUESTS: QuestInput[] = [
  {
    ...base,
    id: "q015",
    number: 15,
    slug: "uc-dakika",
    title: "Üç Dakika",
    subtitle: "Saat yok. Üçte geri dön.",
    description: "Cihazı bırak ve sıradan bir şey yap. Tam üç dakika geçtiğine inandığında geri dön.",
    locationId: "station",
    npcLine: "Yaptığım her saat, ona bakan kişiyle aynı yöne doğru yanılır.",
    family: "predict",
    dimensions: ["estimation"],
    difficulty: 1,
    estimatedMinutes: { min: 2, max: 5 },
    contexts: ["home", "work", "outside", "commuting", "with-people"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    mysteryEligible: true,
    safety: { ...safetyBase, level: "minimal", movement: "none", notes: ["Hiçbir saate bakma — bu ekran da dahil. Burada saat görünmeyecek.", SAFE.notDriving, SAFE.stopAnytime] },
    prime: [
      { id: "intro", kind: "narrative", speaker: "clockmaker", lines: ["Başladığında, göremeyeceğin bir saat çalıştıracağım.", "Saniye sayma. Üç dakika yaşa, sonra geri gel."] },
    ],
    act: {
      instruction: "Sıradan bir şey yap. Tam üç dakika geçtiğini düşündüğünde geri dön.",
      details: ["Sayma. Hiçbir saate bakma."],
      reminder: "Üç dakikada geri gel. Saat yok.",
      targetSeconds: 180,
    },
    reflection: [
      {
        id: "doing",
        kind: "choice",
        role: "reflection",
        prompt: "Beklerken ne yaptın?",
        options: [
          { id: "waited", label: "Çoğunlukla bekledim" },
          { id: "task", label: "Küçük bir iş" },
          { id: "talk", label: "Biriyle konuştum" },
          { id: "wander", label: "Zihnimi serbest bıraktım" },
        ],
      },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Hedef", ref: "act.targetSec", format: "duration" },
          { label: "Döndüğün an", ref: "act.durationSec", format: "duration" },
        ],
        delta: { label: "Fark", a: "act.durationSec", b: "act.targetSec", format: "signed-duration" },
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "act.errorSec", op: "lt", value: -20 }, text: "Üç dakikan erken bitti. Dikkat ettiğin zaman, olduğundan uzun gelir." },
          { when: { ref: "act.errorSec", op: "gt", value: 20 }, text: "Üç dakikan uzadı. Dikkat zamandan uzaklaşınca zaman sayılmadan akıp gider." },
          { text: "Üç dakikaya yirmi saniye yakınlıkta. İç saatin tuttu." },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "doing.optionId", op: "eq", value: "waited" }, text: "Süreyi bekleyerek geçirdin — zamanı genellikle en çok uzatan koşul." },
          { when: { ref: "doing.optionId", op: "eq", value: "wander" }, text: "Zihnini serbest bıraktın; bu, zamanın üzerindeki tutuşu gevşetme eğilimindedir." },
          { text: "Süreyi başka bir şeyle doldurdun; bu, dikkati saatten uzaklaştırır." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "prospective-timing",
        encounter: [
          { when: { ref: "act.errorSec", op: "lt", value: -20 }, text: "Zamanı değerlendireceğini bilerek geçirdiğin üç dakika {act.errorSec|signed-duration} kısa geldi. Zamana dikkat etmek onu uzatma eğilimindedir." },
          { when: { ref: "act.errorSec", op: "gt", value: 20 }, text: "Zamanı değerlendireceğini bilmene rağmen üç dakikan {act.errorSec|signed-duration} uzadı." },
          { text: "Zamanı değerlendireceğini bilerek üç dakikaya {act.absErrorSec|duration} yakınlıkta döndün." },
        ],
      },
    ],
    behaviorSignals: ["prediction-error"],
    worldEffects: [{ kind: "open-path", path: "p-station" }],
    fragment: "İstasyon'da bir saat tıklamaya başlıyor. Akrebi de yelkovanı da yok.",
    nextQuestRules: { suggests: ["q016"] },
    journey: [{ text: "Saatsiz üç dakika: {act.durationSec|duration} sonra döndün." }],
  },
  {
    ...base,
    id: "q016",
    number: 16,
    slug: "durust-saat",
    title: "Dürüst Saat",
    subtitle: "İyi bildiğin bir işi tahmin et.",
    description: "Sürekli yaptığın bir şey seç. Ne kadar sürdüğünü söyle. Sonra Saatçi ölçsün.",
    locationId: "station",
    npcLine: "Bunu bin kez yaptın. Hiç süresini tuttun mu?",
    family: "predict",
    dimensions: ["estimation", "planning"],
    difficulty: 1,
    estimatedMinutes: { min: 5, max: 30 },
    contexts: ["home", "work"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    safety: { ...safetyBase, level: "minimal", movement: "light", notes: ["Normal hızında çalış — bu bir yarış değil.", SAFE.stopAnytime] },
    prime: [
      {
        id: "task",
        kind: "choice",
        role: "decision",
        prompt: "Zaten yapmak üzere olduğun bir iş seç.",
        columns: 2,
        options: [
          { id: "tidy", label: "Bir odayı ya da masayı topla" },
          { id: "dishes", label: "Bulaşık yıka" },
          { id: "ready", label: "Dışarı çıkmaya hazırlan" },
          { id: "messages", label: "Küçük bir mesaj ya da evrak yığınını bitir" },
          { id: "snack", label: "Basit bir atıştırmalık hazırla" },
          { id: "other", label: "Sık yaptığım başka bir şey" },
        ],
      },
      { id: "estimate", kind: "estimate", prompt: "Kaç dakika sürecek?", unit: "min", min: 1, max: 90, step: 1, initial: 10 },
    ],
    act: {
      instruction: "{task.label|text}. Bitirdiğin an geri dön.",
      details: ["Normal hızında çalış — tahmini tutturmak için hızlanma.", "Biter bitmez “Döndüm”e bas."],
      reminder: "{task.label|text}. Normal hız.",
    },
    recall: [
      { id: "actual", kind: "actual", prompt: "Saatçi bunu ölçtü. Hemen dönmediysen düzelt.", unit: "min", source: "act", pairsWith: "estimate", max: 180 },
    ],
    reflection: [
      {
        id: "why",
        kind: "choice",
        role: "reflection",
        prompt: "Süreyi ne belirledi?",
        options: [
          { id: "interruptions", label: "Bölünmeler" },
          { id: "more", label: "Düşündüğümden fazla iş vardı" },
          { id: "pace", label: "Hızım her zamankinden farklıydı" },
          { id: "plan", label: "Hiçbir şey — düşündüğüm gibi gitti" },
        ],
      },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Tahminin", ref: "estimate.value", format: "min" },
          { label: "Gerçek", ref: "actual.value", format: "min" },
        ],
        delta: { label: "Fark", a: "actual.value", b: "estimate.value", format: "signed-min" },
      },
      {
        kind: "text",
        variants: [
          { when: OVER("actual.value", "estimate.value"), text: "Uzadı. Boşluk genellikle, tahmin ederken gözümüzün önüne getirmediğimiz kısımlarda saklanır." },
          { when: UNDER("actual.value", "estimate.value"), text: "Söylediğinden hızlı gitti. Bu iş için tahminlerine pay ekliyor olabilirsin." },
          { text: "Tahminine birkaç dakika yakınlıkta. Bu işi biliyorsun." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "planning-fallacy",
        encounter: [
          { when: OVER("actual.value", "estimate.value"), text: "Sık yaptığın bir iş için {estimate.value|min} tahmin ettin. {actual.value|min} sürdü." },
          { when: UNDER("actual.value", "estimate.value"), text: "{estimate.value|min} tahminine karşılık {actual.value|min} içinde bitirdin — olağan hafife alma eğiliminin tersi." },
          { text: "Tahminin birkaç dakika içinde tuttu ({estimate.value|min} ve {actual.value|min}). Olağan hafife alma eğilimi bu kez görünmedi." },
        ],
      },
    ],
    behaviorSignals: ["prediction-error"],
    fragment: "İstasyon'daki bir kalkış tabelası artık her tren için iki saat gösteriyor: planlanan ve gerçekleşen.",
    nextQuestRules: { suggests: ["q017"] },
    journey: [{ text: "{task.label|text}: {estimate.value|min} tahmin edildi, {actual.value|min} sürdü." }],
  },
  {
    ...base,
    id: "q017",
    number: 17,
    slug: "capa",
    title: "Çapa",
    subtitle: "Önce bir sayı gelir.",
    description: "Kısa bir yürüyüşü tahmin etmeden önce Saatçi bir sayıdan bahsediyor. Hiçbir anlamı olmayabilir.",
    locationId: "station",
    npcLine: "Sana bir sayı vereceğim. Onunla ne istersen yap.",
    family: "predict",
    dimensions: ["estimation", "decision-making"],
    difficulty: 2,
    estimatedMinutes: { min: 10, max: 30 },
    contexts: ["home", "outside"],
    energy: "normal",
    people: "solo",
    requiresOutside: true,
    requiresLocation: "Yürüyerek gidip gelebileceğin bir yer",
    availability: { requiresCampaignProgress: 1 },
    safety: { ...safetyBase, level: "low", movement: "walking", notes: [SAFE.publicKnown, SAFE.nothingToBuy, SAFE.eyesUp, SAFE.stopAnytime] },
    prime: [
      {
        id: "destination",
        kind: "choice",
        role: "decision",
        prompt: "Yürüyerek gidip gelebileceğin bir yer seç.",
        options: [
          { id: "shop", label: "En yakın bakkal", hint: "Yalnızca kapısına kadar — hiçbir şey satın almana gerek yok." },
          { id: "stop", label: "En yakın otobüs ya da tramvay durağı" },
          { id: "green", label: "En yakın park ya da yeşil alan" },
          { id: "landmark", label: "Evden görebildiğin bir nirengi noktası" },
        ],
      },
      {
        id: "estimate",
        kind: "estimate",
        prompt: "Gidiş-dönüş kaç dakika sürecek?",
        unit: "min",
        min: 1,
        max: 90,
        step: 1,
        initial: 15,
        anchor: { prompt: "Gidiş-dönüş {anchor} dakikadan uzun mu, kısa mı?", values: [5, 40] },
      },
    ],
    act: {
      instruction: "Seçtiğin yere yürü ve geri dön: {destination.label|phrase}.",
      details: ["Normal hızında. Tahminine uymak için acele etme.", "Döndüğünde “Döndüm”e bas."],
      reminder: "Git ve dön. Normal hız.",
    },
    recall: [
      { id: "actual", kind: "actual", prompt: "Saatçi ölçtü. Hemen dönmediysen düzelt.", unit: "min", source: "act", pairsWith: "estimate", max: 180 },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "İlk gördüğün sayı", ref: "estimate.anchor", format: "min" },
          { label: "Tahminin", ref: "estimate.value", format: "min" },
          { label: "Gerçek", ref: "actual.value", format: "min" },
        ],
      },
      {
        kind: "text",
        variants: [
          {
            when: { all: [{ ref: "estimate.anchor", op: "gte", value: 30 }, { compare: { a: "estimate.value", op: "gt", b: "actual.value", ratio: 1.2 } }] },
            text: "İlk sayı yüksekti ve tahminin gerçek sürenin epey üstüne düştü.",
          },
          {
            when: { all: [{ ref: "estimate.anchor", op: "lt", value: 30 }, { compare: { a: "estimate.value", op: "lt", b: "actual.value", ratio: 0.8 } }] },
            text: "İlk sayı düşüktü ve tahminin gerçek sürenin epey altına düştü.",
          },
          { text: "Tahminin ilk sayıya doğru belirgin biçimde eğilmedi." },
        ],
      },
      { kind: "text", variants: [{ text: "Tek bir yürüyüş, sayının seni etkileyip etkilemediğini gösteremez. Bunun için aynı sorunun farklı bir ilk sayıyla sorulması gerekir — çapalama tam da böyle incelenir." }] },
    ],
    discoveries: [
      { discovery: "anchoring", encounter: [{ text: "Tahmin etmeden önce sana {estimate.anchor|min} soruldu. {estimate.value|min} tahmin ettin; yol {actual.value|min} sürdü." }] },
    ],
    behaviorSignals: ["prediction-error", "anchor-exposure"],
    fragment: "Biri İstasyon'da bir perona bir sayı boyamış. Yolcular dönüp dönüp ona bakıyor.",
    nextQuestRules: { suggests: ["q018"] },
    journey: [{ text: "Gidiş-dönüş ({destination.label|phrase}): {estimate.value|min} tahmin edildi, {actual.value|min} sürdü." }],
  },
  {
    ...base,
    id: "q018",
    number: 18,
    slug: "ayak-isleri-plani",
    title: "Ayak İşleri Planı",
    subtitle: "Dört şey planla. Sonra yeniden planla.",
    description: "Bir avuç küçük iş ve bir zaman bütçesi. Plan tam oturduğu anda bir şey değişiyor.",
    locationId: "market",
    npcLine: "Planlar güzel şeylerdir. Hiçbirinin sapasağlam kaldığını görmedim.",
    family: "decide",
    dimensions: ["planning", "adaptation", "estimation"],
    difficulty: 2,
    estimatedMinutes: { min: 15, max: 30 },
    contexts: ["home", "work"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 2 },
    safety: { ...safetyBase, level: "minimal", movement: "light", notes: ["Bütün işler küçük ve bulunduğun yerde yapılıyor. Mümkün olmayanları atla.", SAFE.stopAnytime] },
    prime: [
      {
        id: "plan",
        kind: "priority-board",
        prompt: "Bunları yapacağın sıraya diz. 20 dakikan var — bir şey sığmayacak.",
        droppable: true,
        budgetMinutes: 20,
        items: [
          { id: "water", label: "Bitkileri sula ya da şişeleri doldur", minutes: 3 },
          { id: "desk", label: "Bir masayı ya da sehpayı boşalt", minutes: 6 },
          { id: "list", label: "Yarının kısa listesini yaz", minutes: 4 },
          { id: "sort", label: "Bir çamaşır ya da kâğıt yığınını ayıkla", minutes: 7 },
          { id: "reply", label: "Ertelediğin bir mesajı yanıtla", minutes: 5 },
        ],
      },
      { id: "twist", kind: "twist", title: "Bir şey çıktı.", body: "Mesaj bekleyemez. En başa geçiyor — ve artık 20 değil, 15 dakikan var." },
      {
        id: "replan",
        kind: "priority-board",
        prompt: "Yeniden planla. Mesaj en başta; 15 dakika.",
        revises: "plan",
        droppable: true,
        budgetMinutes: 15,
        constraints: [
          { kind: "first", item: "reply" },
          { kind: "keep", item: "reply" },
        ],
      },
      { id: "estimate", kind: "estimate", prompt: "Dürüstçe: yeni plan ne kadar sürecek?", unit: "min", min: 1, max: 60, step: 1, initial: 15 },
    ],
    act: {
      instruction: "Yeni planı, yeni sıranla uygula.",
      details: ["Mümkün olmadığı ortaya çıkan her şeyi atla."],
      reminder: "Yeni plan, sırasıyla.",
    },
    recall: [
      { id: "actual", kind: "actual", prompt: "Ölçüldü. Gerekirse düzelt.", unit: "min", source: "act", pairsWith: "estimate", max: 120 },
      {
        id: "survived",
        kind: "choice",
        role: "recall",
        prompt: "Plan ayakta kaldı mı?",
        options: [
          { id: "exact", label: "Tam planlandığı gibi" },
          { id: "mostly", label: "Çoğunlukla — küçük değişiklikler" },
          { id: "broke", label: "Dağıldı" },
        ],
      },
    ],
    reveal: [
      { kind: "plan", before: "plan", after: "replan" },
      {
        kind: "figures",
        items: [
          { label: "Tahminin", ref: "estimate.value", format: "min" },
          { label: "Gerçek", ref: "actual.value", format: "min" },
        ],
        delta: { label: "Fark", a: "actual.value", b: "estimate.value", format: "signed-min" },
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "replan.positionsChanged", op: "gte", value: 3 }, text: "Sürprizden sonra {replan.positionsChanged|count} sırayı değiştirdin — yama değil, gerçek bir yeniden plan." },
          { text: "Sürprizden sonra olabildiğince az şey değiştirdin: {replan.positionsChanged|count} sıra oynadı." },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "survived.optionId", op: "eq", value: "exact" }, text: "Sonra plan tam tuttu. Sürpriz sen başlamadan emilmişti." },
          { when: { ref: "survived.optionId", op: "eq", value: "mostly" }, text: "Sonra plan esnedi ve tuttu." },
          { text: "Sonra plan temas anında dağıldı. Bu, senin hakkında değil planın hakkında bir bilgi." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "planning-fallacy",
        when: OVER("actual.value", "estimate.value"),
        encounter: [{ text: "Bir sürprize göre yeniden plan yaptıktan sonra bile iş, tahmin ettiğin {estimate.value|min} yerine {actual.value|min} sürdü." }],
      },
    ],
    behaviorSignals: ["plan-revision", "prediction-error"],
    fragment: "Çarşı'da bir tezgâhtar günün fiyatlarını tebeşirle iki kez yeniden yazıyor.",
    nextQuestRules: { suggests: ["q019"] },
    journey: [{ text: "Sürprizden sonra yeniden planlandı ({replan.positionsChanged|count} sıra oynadı). {estimate.value|min} tahmin edildi, {actual.value|min} sürdü." }],
  },
  {
    ...base,
    id: "q019",
    number: 19,
    slug: "bolunme",
    title: "Bölünme",
    subtitle: "İki liste. İki yol.",
    description: "Kâğıda iki kısa liste yaz — bir kez bloklar hâlinde, bir kez karışık. Saatçi ikisini de ölçer.",
    locationId: "workshop",
    npcLine: "Geçiş yapmak bedava gibi gelir. Hadi ona bir fiyat biçelim.",
    family: "create",
    dimensions: ["task-switching", "planning"],
    difficulty: 2,
    estimatedMinutes: { min: 5, max: 10 },
    contexts: ["home", "work"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    requiresLocation: "Kâğıt ve kalemin olduğu bir yer",
    availability: { requiresCampaignProgress: 3 },
    safety: { ...safetyBase, level: "minimal", movement: "none", notes: ["Kâğıt ve kaleme ihtiyacın olacak. Yazdığın hiçbir şey buraya girilmez.", SAFE.stopAnytime] },
    prime: [
      { id: "warm", kind: "rule-shift", instruction: "Her işareti gösterilen kurala göre ayır. Kural değişir.", rules: ["shape", "fill"], trials: 20, runLength: [3, 5] },
      { id: "brief", kind: "narrative", speaker: "clockmaker", lines: ["Şimdi kâğıt üzerinde. Ayrı ayrı ölçülen iki bölüm.", "Aralarında ekrana dokun. Ekran bu seferlik masada yüzü yukarı durabilir."] },
    ],
    act: {
      instruction: "Kâğıt üzerinde süresi ölçülen iki bölüm. Aralarında dokun.",
      details: ["İkinci bölümde yeni hayvanlar ve şehirler kullan — tekrar yok."],
      reminder: "Kâğıt, kalem. Bölümler arasında dokun.",
      segments: [
        { id: "block", label: "Birinci bölüm — bloklar hâlinde", instruction: "On hayvan yaz. Sonra on şehir." },
        { id: "mixed", label: "İkinci bölüm — karışık", instruction: "On yeni hayvan ve on yeni şehir, sırayla: hayvan, şehir, hayvan, şehir…" },
      ],
    },
    reflection: [
      {
        id: "felt",
        kind: "choice",
        role: "reflection",
        prompt: "Hangisi daha zor geldi?",
        options: [
          { id: "block", label: "Bloklar" },
          { id: "mixed", label: "Karışık" },
          { id: "same", label: "Aşağı yukarı aynı" },
        ],
      },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Bloklar hâlinde", ref: "act.segments.block", format: "duration" },
          { label: "Karışık", ref: "act.segments.mixed", format: "duration" },
        ],
        delta: { label: "Fark", a: "act.segments.mixed", b: "act.segments.block", format: "signed-duration" },
      },
      {
        kind: "text",
        variants: [
          { when: { compare: { a: "act.segments.mixed", op: "gt", b: "act.segments.block", ratio: 1.1 } }, text: "Karışık yazmak daha uzun sürdü. Kategoriler arasındaki her geçiş küçük bir ücret kesti." },
          { when: { compare: { a: "act.segments.mixed", op: "lt", b: "act.segments.block", ratio: 0.95 } }, text: "Karışık yazmak daha hızlıydı — kısmen alıştırma, çünkü ikinci sıradaydı. Daha adil bir sınama, bir dahaki sefere sırayı değiştirmek olur." },
          { text: "Neredeyse hiç fark yok. Ya geçiş senin için ucuzdu ya da birinci bölümdeki alıştırma bedelini ödedi." },
        ],
      },
      { kind: "switch", ref: "warm" },
    ],
    discoveries: [
      {
        discovery: "task-switching-cost",
        when: { compare: { a: "act.segments.mixed", op: "gt", b: "act.segments.block", ratio: 1.1 } },
        encounter: [{ text: "Karışık listeler {act.segments.mixed|duration} sürdü; aynı türden iş bloklar hâlinde {act.segments.block|duration} sürdü." }],
      },
    ],
    behaviorSignals: ["switch-cost", "experiment"],
    fragment: "Atölye'de iki özdeş alet yan yana asılı. Biri, sürekli alınıp bırakılmaktan aşınmış.",
    nextQuestRules: { suggests: ["q020"] },
    journey: [{ text: "Bloklar: {act.segments.block|duration}. Karışık: {act.segments.mixed|duration}." }],
  },
  {
    ...base,
    id: "q020",
    number: 20,
    slug: "uzun-dakika",
    title: "Uzun Dakika",
    subtitle: "Zamanın izini kaybet. Sonra tahmin et.",
    description: "Saate bakmadan seni içine çeken bir şey yap. Döndüğünde ne kadar uzakta kaldığını tahmin et.",
    locationId: "garden",
    npcLine: "İzlemediğin zaman bir yere gider. Hadi nereye gittiğini bulalım.",
    family: "predict",
    dimensions: ["estimation"],
    difficulty: 1,
    estimatedMinutes: { min: 15, max: 30 },
    contexts: ["home", "work", "outside"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    mysteryEligible: true,
    availability: { requiresCampaignProgress: 2 },
    safety: { ...safetyBase, level: "minimal", movement: "light", notes: ["Sakin ve tanıdık bir şey seç.", SAFE.stopAnytime] },
    prime: [
      {
        id: "activity",
        kind: "choice",
        role: "decision",
        prompt: "Seni içine çeken bir şey seç.",
        options: [
          { id: "read", label: "Okumak" },
          { id: "draw", label: "Çizmek ya da karalamak" },
          { id: "walk", label: "Hoş bir yerde yürümek" },
          { id: "tidy", label: "Yavaşça toparlamak" },
          { id: "music", label: "Başka bir şey yapmadan müzik dinlemek" },
        ],
      },
      { id: "brief", kind: "narrative", speaker: "clockmaker", lines: ["Saate bakma. İçinden geldiğinde dön — aşağı yukarı çeyrek saat sonra."] },
    ],
    act: {
      instruction: "{activity.label|text}, saate bakmadan.",
      details: ["İçinden geldiğinde geri gel."],
      reminder: "Saat yok. Doğru gelince dön.",
    },
    recall: [
      { id: "retro", kind: "estimate", prompt: "Hiçbir şey görmeden önce: kaç dakikadır uzaktaydın?", unit: "min", min: 1, max: 120, step: 1, initial: 15 },
      { id: "actual", kind: "actual", prompt: "Saatçi'nin ölçtüğü.", unit: "min", source: "act", pairsWith: "retro", max: 240 },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Sana gelen", ref: "retro.value", format: "min" },
          { label: "Gerçek", ref: "actual.value", format: "min" },
        ],
        delta: { label: "Fark", a: "actual.value", b: "retro.value", format: "signed-min" },
      },
      {
        kind: "text",
        variants: [
          { when: OVER("actual.value", "retro.value"), text: "Hissettiğinden uzun süre uzaktaydın. İçine çekilerek geçen zaman arkasında daha az iz bırakır." },
          { when: UNDER("actual.value", "retro.value"), text: "Olduğundan uzun geldi. Bazı zaman dilimleri küçük olaylarla doludur." },
          { text: "Yakın. Geçen zaman duygun saatsiz de tuttu." },
        ],
      },
    ],
    discoveries: [
      { discovery: "prospective-timing", encounter: [{ text: "Geçerken ölçmediğin {actual.value|min}, sana {retro.value|min} gibi geldi. Zamanı sonradan değerlendirmek, onu akarken izlemekten farklı ipuçlarına dayanır." }] },
    ],
    behaviorSignals: ["prediction-error"],
    fragment: "Bahçe'de bir güneş saati bilerek düzeltilmeden bırakılmış.",
    nextQuestRules: { suggests: ["q021"] },
    journey: [{ text: "{activity.label|text}: {retro.value|min} gibi geldi, {actual.value|min} sürdü." }],
  },
  {
    ...base,
    id: "q021",
    number: 21,
    slug: "kalkis-tabelasi",
    title: "Kalkış Tabelası",
    subtitle: "Üç durak, tek tarife.",
    description: "Üç duraklı kısa bir gezi planla ve tamamını tahmin et. Yol üzerinde bir yerde mühürlü bir not seni bekliyor.",
    locationId: "station",
    npcLine: "İstasyon tahminlerle döner. Hadi seninkini tabelaya yazalım.",
    family: "predict",
    dimensions: ["planning", "estimation", "adaptation"],
    difficulty: 3,
    estimatedMinutes: { min: 30, max: 60 },
    contexts: ["outside"],
    energy: "high",
    people: "solo",
    requiresOutside: true,
    requiresLocation: "Yürüme mesafesinde birkaç kamuya açık yer olan bir mahalle",
    availability: { requiresCampaignProgress: 5 },
    safety: {
      ...safetyBase,
      level: "moderate",
      movement: "walking",
      notes: ["Kamuya açık ve ücretsiz ziyaret edilebilen duraklar seç.", SAFE.nothingToBuy, "Yürürken cihazı kaldır. Mühürlü notu ancak durduktan sonra aç.", "Geziyi istediğin zaman kısa kes."],
    },
    prime: [
      {
        id: "route",
        kind: "priority-board",
        prompt: "Üç durak seç ve sıraya koy. Birini kenara bırak.",
        droppable: true,
        budgetMinutes: 40,
        items: [
          { id: "board", label: "Bir ilan panosu ya da posta kutusu", minutes: 10 },
          { id: "green", label: "Sevdiğin bir park, meydan ya da ağaç", minutes: 12 },
          { id: "high", label: "Yürüyerek ulaşabileceğin en yüksek nokta", minutes: 15 },
          { id: "bench", label: "Manzaralı bir bank", minutes: 8 },
        ],
      },
      { id: "estimate", kind: "estimate", prompt: "Kapıdan kapıya bütün gezi ne kadar sürecek?", unit: "min", min: 10, max: 120, step: 1, initial: 35 },
    ],
    act: {
      instruction: "Rotanı kendi sıranla yürü.",
      details: ["Her durakta bir an dur ve devam etmeden önce etrafına bak."],
      reminder: "Senin rotan, senin sıran. İkinci durakta mühürlü bir not bekliyor.",
      sealed: { trigger: "İkinci durağa vardığında aç.", body: "Burada, görüş alanındaki herhangi bir yerde yazılı en eski tarihi bul — bir tabela, bir taş, bir plaket. Sonra devam et." },
    },
    recall: [
      { id: "actual", kind: "actual", prompt: "Ölçüldü. Gerekirse düzelt.", unit: "min", source: "act", pairsWith: "estimate", max: 240 },
      {
        id: "order",
        kind: "choice",
        role: "recall",
        prompt: "Planladığın sırayı korudun mu?",
        options: [
          { id: "kept", label: "Korudum" },
          { id: "changed", label: "Yolda değiştirdim" },
          { id: "cut", label: "Bir durağı atladım" },
        ],
      },
      { id: "oldest", kind: "text", prompt: "Bulduğun en eski tarih", hint: "İsteğe bağlı." },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Tahminin", ref: "estimate.value", format: "min" },
          { label: "Gerçek", ref: "actual.value", format: "min" },
        ],
        delta: { label: "Fark", a: "actual.value", b: "estimate.value", format: "signed-min" },
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "order.optionId", op: "eq", value: "kept" }, text: "Rota planladığın sırayla aktı." },
          { when: { ref: "order.optionId", op: "eq", value: "changed" }, text: "Rota yolda değişti. Masa başında yapılan planlar, hayal etmedikleri sokaklarla karşılaşır." },
          { text: "Bir durağı atladın. Tabela üç diyordu; gün daha azını söyledi." },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "oldest.text", op: "exists" }, text: "İkinci durakta bulunan en eski tarih: {oldest.text|text}." },
          { when: { ref: "act.sealedOpened", op: "eq", value: true }, text: "Mühürlü notu ikinci durakta açtın." },
          { text: "Mühürlü not mühürlü kaldı." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "planning-fallacy",
        when: OVER("actual.value", "estimate.value"),
        encounter: [{ text: "Durak durak planlanan üç duraklı gezi, senin {estimate.value|min} tahminine karşılık {actual.value|min} sürdü." }],
      },
    ],
    behaviorSignals: ["prediction-error", "plan-revision"],
    fragment: "İstasyon'un ana tabelası yeni bir satıra dönüyor: SENİN ROTAN — KALKTI.",
    journey: [{ text: "Üç duraklı gezi: {estimate.value|min} tahmin edildi, {actual.value|min} sürdü." }],
  },
];
