/** Kampanya 1 — OTOPİLOTU KIR. Alışkanlıkları böl; tanıdık yerleri yeniden gör. */
import type { QuestInput } from "@/domain/content-types";
import { SAFE } from "./safety-notes";

const base = {
  version: 1,
  campaignId: "autopilot",
  npcId: "cartographer",
  requiresPurchase: false as const,
};

export const AUTOPILOT_QUESTS: QuestInput[] = [
  {
    ...base,
    id: "q001",
    number: 1,
    slug: "sapak",
    title: "Sapak",
    subtitle: "Başka bir yoldan git.",
    description: "Gözün kapalı yürüyebileceğin bir yol var. Bugün o yoldan gitme.",
    locationId: "crossroads",
    npcLine: "Bana yüz kere çizmek zorunda kalmadığım bir çizgi ver.",
    family: "explore",
    dimensions: ["attention", "adaptation"],
    difficulty: 1,
    estimatedMinutes: { min: 10, max: 25 },
    contexts: ["outside", "commuting"],
    energy: "normal",
    people: "solo",
    requiresOutside: true,
    requiresLocation: "Sık yürüdüğün bir yol — bir durağa, dükkâna ya da eve",
    mysteryEligible: true,
    safety: {
      level: "low",
      movement: "walking",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: [SAFE.publicKnown, SAFE.eyesUp, SAFE.notDriving, "Yeni yol içine sinmezse geri dön. Yine de sayılır.", SAFE.stopAnytime],
    },
    prime: [
      { id: "intro", kind: "narrative", speaker: "cartographer", lines: ["Sık yürüdüğün bir yolu düşün.", "Onu değiştirmeden önce, yol boyunca neyin yanından geçmeyi beklediğini yaz."] },
      { id: "usual", kind: "list", role: "prime", prompt: "Her zamanki yolda hep yanından geçtiğin üç şeyi yaz.", slots: 3, required: 3, placeholder: "ör. mavi bir kapı" },
    ],
    act: {
      instruction: "Aynı yere başka bir yoldan git.",
      details: ["Güvenli her sapak sayılır — paralel bir sokak, parkın öbür yanı, bir önceki dönüş.", "Normal hızında yürü. Her zamankinden daha çok etrafına bak."],
      reminder: "Başka bir yol. Aynı varış noktası.",
    },
    recall: [
      { id: "new", kind: "list", role: "recall", prompt: "Yeni yolda neleri fark ettin?", hint: "En fazla beş şey.", slots: 5, required: 1, placeholder: "ör. banklı bir avlu" },
      {
        id: "drift",
        kind: "choice",
        role: "recall",
        prompt: "Ayakların her zamanki yola sapmaya çalıştı mı?",
        options: [
          { id: "often", label: "Birden fazla kez" },
          { id: "once", label: "Bir kez" },
          { id: "never", label: "Hiç" },
        ],
      },
    ],
    reflection: [{ id: "strange", kind: "scale", prompt: "Sapak ne kadar yabancı geldi?", lowLabel: "Neredeyse aynı", highLabel: "Başka bir şehir gibi" }],
    reveal: [
      { kind: "list", ref: "usual", label: "Her zamanki yolda beklediklerin" },
      { kind: "list", ref: "new", label: "Sapağın sana gösterdikleri" },
      {
        kind: "text",
        variants: [
          { when: { ref: "drift.optionId", op: "eq", value: "often" }, text: "Ayakların seni sürekli her zamanki yola doğru çekti. Alışkanlık yol boyunca senden bir adım öndeydi." },
          { when: { ref: "drift.optionId", op: "eq", value: "once" }, text: "Bir kez eski yol seni çekti. Alışkanlıklar kapanmaz; oylamada kaybederler." },
          { text: "Yeni çizgiyi baştan sona tuttun. Her zamanki yol haritada kaldı, kullanılmadan." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "habituation",
        encounter: [
          { text: "Her zamanki yolu yürümeden sayabildin — ama sapakta {new.count|count} şey dikkatine takıldı; alışık yol artık bunları sunmuyor. Tanıdık yollar fark edilmez olur." },
        ],
      },
    ],
    behaviorSignals: ["routines-interrupted", "details-recalled"],
    completionRules: { interruptsRoutine: true },
    worldEffects: [{ kind: "open-path", path: "p-workshop" }],
    fragment: "Kavşak'ın batısında daha önce hiç kullanmadığın bir sokak haritada beliriyor. Henüz ölçülmemiş bir yere çıkıyor.",
    nextQuestRules: { suggests: ["q003"] },
    journey: [{ text: "Başka bir yoldan gittin. {new.count|count} yeni şey fark edildi." }],
  },
  {
    ...base,
    id: "q002",
    number: 2,
    slug: "ters-el",
    title: "Ters El",
    subtitle: "Öbür elin öne geçsin.",
    description: "Baskın elin sana sormadan yüz küçük iş yapıyor. On dakika boyunca beklemek zorunda.",
    locationId: "workshop",
    npcLine: "Alışkanlıklar o kadar sık çizilmiş kestirmelerdir ki duvara dönüşmüşlerdir. Bakalım bu duvar nerede duruyor.",
    family: "break",
    dimensions: ["inhibition", "task-switching"],
    difficulty: 1,
    estimatedMinutes: { min: 5, max: 12 },
    contexts: ["home", "work"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    mysteryEligible: true,
    safety: {
      level: "minimal",
      movement: "light",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: [SAFE.gentleHands, SAFE.stopAnytime],
    },
    prime: [
      { id: "intro", kind: "narrative", speaker: "cartographer", lines: ["Önce eller için bir ısınma.", "Kural pek haber vermeden değişecek. Ayak uydur."] },
      { id: "switch", kind: "rule-shift", instruction: "Gösterilen kurala göre cevap ver. Kural değişecek.", rules: ["side-same", "side-opposite"], trials: 24, runLength: [3, 6] },
    ],
    act: {
      instruction: "On dakika boyunca küçük rutin işler için baskın olmayan elini kullan.",
      details: ["Kapılar, ışık düğmeleri, bardaklar, fare, telefonun — düşünmeden yaptığın her şey.", "Her zamanki elini çoktan hareket etmişken yakaladığında say."],
      reminder: "Öbür el önde. Her zamankinin kaç kez denediğini say.",
    },
    recall: [
      { id: "caught", kind: "count", prompt: "Her zamanki elini kaç kez çoktan hareket etmişken yakaladın?", hint: "Dürüst bir tahmin yeterli.", max: 60 },
      {
        id: "hardest",
        kind: "choice",
        role: "recall",
        prompt: "Devretmesi en zor olan neydi?",
        columns: 2,
        options: [
          { id: "doors", label: "Kapılar ve kulplar" },
          { id: "screens", label: "Telefon ya da fare" },
          { id: "drink", label: "Yemek ya da içmek" },
          { id: "writing", label: "Yazmak" },
          { id: "other", label: "Başka bir şey" },
        ],
      },
    ],
    reflection: [{ id: "effort", kind: "scale", prompt: "Ne kadar dikkat gerektirdi?", lowLabel: "Neredeyse hiç", highLabel: "Tamamını" }],
    reveal: [
      { kind: "switch", ref: "switch" },
      {
        kind: "text",
        variants: [
          { when: { ref: "switch.switchCostMs", op: "gt", value: 60 }, text: "Her kural değişiminin hemen ardından tepkilerin {switch.switchCostMs|ms} yavaşladı. Yeni kural yerleşince hız geri geldi." },
          { text: "Kural değişimleri seni pek yavaşlatmadı (değişimden sonraki ilk tepkide {switch.switchCostMs|signed-ms}). Kısa, net kurallar geçişi ucuzlatır." },
        ],
      },
      { kind: "figures", items: [{ label: "Her zamanki elin önce davrandı", ref: "caught.value", format: "count" }] },
      {
        kind: "text",
        variants: [
          { when: { ref: "caught.value", op: "gte", value: 1 }, text: "Dışarıda eski alışkanlık {caught.value|count} kez önce davrandı. Her biri, sen karar vermeden verilmiş bir karardı." },
          { text: "Her zamanki elini önce davranırken yakalamadın. Ya değiş tokuş kolaydı — ya da alışkanlık fark edilmeyecek kadar sessiz çalıştı." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "capture-error",
        when: { ref: "caught.value", op: "gte", value: 1 },
        encounter: [{ text: "Baskın elin {caught.value|count} kez önce davrandı — alışılmış bir rutin, daha az alışılmış olanı yakaladı." }],
      },
      {
        discovery: "task-switching-cost",
        when: { ref: "switch.switchCostMs", op: "gt", value: 60 },
        encounter: [{ text: "Isınmada her kural değişiminden sonraki ilk tepki, ardından gelenlerden {switch.switchCostMs|ms} daha uzun sürdü." }],
      },
    ],
    behaviorSignals: ["switch-cost", "routines-interrupted"],
    completionRules: { interruptsRoutine: true },
    fragment: "Atölye'de toz tutmuş bir tezgâh yeniden kullanılıyor — beceriksizce, ters elle.",
    nextQuestRules: { suggests: ["q006"] },
    journey: [{ text: "{act.durationMin|min} boyunca öbür el. Her zamanki el {caught.value|count} kez önce davrandı." }],
  },
  {
    ...base,
    id: "q003",
    number: 3,
    slug: "tanidik-oda",
    title: "Tanıdık Oda",
    subtitle: "Onu hafızandan kur. Sonra kontrol et.",
    description: "Vakit geçirdiğin bir oda seç — şu an içinde olmadığın bir oda. Onu iyi tanıyorsun. Ya da öyle sanıyorsun.",
    locationId: "archive",
    npcLine: "Arşiv, bildiğin her yerin bir kopyasını saklar. Kopyalar kayar.",
    family: "remember",
    dimensions: ["recall", "attention"],
    difficulty: 1,
    estimatedMinutes: { min: 5, max: 10 },
    contexts: ["home", "work"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    requiresLocation: "Yakında, rahatça girebileceğin bir oda",
    safety: {
      level: "minimal",
      movement: "light",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: ["Rahatça girebileceğin bir oda seç.", SAFE.stopAnytime],
    },
    prime: [
      { id: "intro", kind: "narrative", speaker: "cartographer", lines: ["Yakında, şu an içinde olmadığın bir oda seç.", "Gözünün önüne getir. Henüz oraya gitme."] },
      { id: "remembered", kind: "list", role: "prime", prompt: "O odadaki beş şeyi ve nerede durduklarını yaz.", slots: 5, required: 3, placeholder: "ör. kapının üstünde saat" },
    ],
    act: {
      instruction: "Odaya git. Kapı eşiğinde dur ve iki dakika bak.",
      details: ["Listendeki her şeyi kontrol et: orada mı, söylediğin yerde mi?", "Sonra listeye hiç yazmadığın her şeye bak."],
      reminder: "Kapı eşiği. İki dakika. Karşılaştır.",
    },
    recall: [
      {
        id: "check",
        kind: "item-check",
        prompt: "Listen ne kadar tuttu?",
        source: "remembered",
        options: [
          { id: "there", label: "Söylediğim yerde" },
          { id: "moved", label: "Başka yerde" },
          { id: "missing", label: "Yok" },
        ],
      },
      { id: "unlisted", kind: "count", prompt: "Listelemediğin kaç şey fark ettin?", max: 60 },
    ],
    reflection: [
      {
        id: "surprise",
        kind: "choice",
        role: "reflection",
        prompt: "Seni en çok ne şaşırttı?",
        options: [
          { id: "position", label: "Eşyaların gerçekte nerede olduğu" },
          { id: "absence", label: "Beklediğim bir şeyin orada olmaması" },
          { id: "unseen", label: "Görmeyi bıraktığım bir şey" },
          { id: "nothing", label: "Hiçbir şey — birebir tuttu" },
        ],
      },
    ],
    reveal: [
      { kind: "list", ref: "remembered", label: "Odanın senin kopyası" },
      {
        kind: "figures",
        items: [
          { label: "Söylediğin yerde", ref: "check.counts.there", format: "count" },
          { label: "Başka yerde", ref: "check.counts.moved", format: "count" },
          { label: "Yok", ref: "check.counts.missing", format: "count" },
          { label: "Hiç yazılmamış", ref: "unlisted.value", format: "count" },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "unlisted.value", op: "gte", value: 5 }, text: "Kopyan senin için önemli olanı tutuyordu. Oda ise görmeyi bıraktığın {unlisted.value|count} şey daha barındırıyordu." },
          { text: "Kopyan ile oda birbirine yakındı. {unlisted.value|count} şey sessizce kopyadan düşmüştü." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "habituation",
        encounter: [
          { when: { ref: "unlisted.value", op: "gte", value: 1 }, text: "Çok iyi bildiğin bir odadaki {unlisted.value|count} şey, o odanın hafızandaki hâline girmemişti. Değişmeyen şeyler fark edilmez olur." },
          { text: "Hafızan odayla neredeyse birebir örtüştü — değişmeyen şeylerin fark edilmez olduğu bu kadar tanıdık bir yer için alışılmadık." },
        ],
      },
    ],
    behaviorSignals: ["details-recalled"],
    fragment: "Arşiv'de biri eski bir kat planını kurşun kalemle düzeltiyor.",
    nextQuestRules: { suggests: ["q004"] },
    journey: [{ text: "Bir odayı hafızadan kurdun: {remembered.count|count} şeyden {check.counts.there|count} tanesi söylediğin yerdeydi." }],
  },
  {
    ...base,
    id: "q004",
    number: 4,
    slug: "yer-degistir",
    title: "Yer Değiştir",
    subtitle: "Aynı yer. Farklı koltuk.",
    description: "Uzun zamandır aynı yerlere aynı açıdan bakıyorsun. Kıpırda.",
    locationId: "observatory",
    npcLine: "Tek bir köşeden çizilen harita, yarım haritadır.",
    family: "explore",
    dimensions: ["attention", "adaptation"],
    difficulty: 1,
    estimatedMinutes: { min: 3, max: 10 },
    contexts: ["home", "work", "commuting"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 1 },
    safety: {
      level: "minimal",
      movement: "light",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: ["Yalnızca boş ve sana ait bir yere geç.", SAFE.notDriving, SAFE.stopAnytime],
    },
    prime: [
      {
        id: "expect",
        kind: "choice",
        role: "decision",
        prompt: "Yer değiştirmeden önce: en çok neyin değişeceğini düşünüyorsun?",
        options: [
          { id: "view", label: "Görebildiklerim" },
          { id: "sound", label: "Duyabildiklerim" },
          { id: "feel", label: "Orada olmanın hissi" },
          { id: "people", label: "Çevremdeki alanın işleyişi" },
          { id: "nothing", label: "Pek bir şey" },
        ],
      },
    ],
    act: {
      instruction: "Hiç oturmadığın ya da durmadığın bir yere geç — öbür sandalye, masanın öbür ucu, vagonun öbür tarafı.",
      details: ["En az üç dakika orada kal.", "Etrafına yeni gelmiş gibi bak."],
      reminder: "Yeni yer. Üç dakika. Yeniden var ol.",
    },
    recall: [
      {
        id: "found",
        kind: "choice",
        role: "recall",
        prompt: "Gerçekte en çok ne değişti?",
        options: [
          { id: "view", label: "Görebildiklerim" },
          { id: "sound", label: "Duyabildiklerim" },
          { id: "feel", label: "Orada olmanın hissi" },
          { id: "people", label: "Çevremdeki alanın işleyişi" },
          { id: "nothing", label: "Pek bir şey" },
        ],
      },
      { id: "noticed", kind: "list", role: "recall", prompt: "Oradan daha önce göremediğin ya da duyamadığın ne vardı?", slots: 4, required: 1 },
    ],
    reflection: [{ id: "again", kind: "scale", prompt: "Orada yine oturur muydun?", lowLabel: "Hayır — eski yerim daha iyi", highLabel: "Artık benim yerim" }],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Beklediğin", ref: "expect.label", format: "text" },
          { label: "Bulduğun", ref: "found.label", format: "text" },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { compare: { a: "expect.optionId", op: "eq", b: "found.optionId" } }, text: "Tam da bulmayı beklediğin şeyi buldun. Belli bir değişiklik beklediğimizde onu ararız — ve görürüz." },
          { text: "En büyük değişiklik, hiç bakmadığın bir yerden geldi." },
        ],
      },
      { kind: "list", ref: "noticed", label: "Yalnızca öbür yerden görünenler" },
    ],
    discoveries: [
      {
        discovery: "confirmation-bias",
        when: { compare: { a: "expect.optionId", op: "eq", b: "found.optionId" } },
        encounter: [{ text: "Neyin değişeceğini tahmin ettin — {expect.label|phrase} — ve sonra tam olarak onu buldun. Beklenti, dikkatin nereye gideceğini belirler." }],
      },
    ],
    behaviorSignals: ["prediction-match"],
    completionRules: { interruptsRoutine: true },
    fragment: "Gözlemevi'nin hiç kullanmadığın bir penceresinden uzakta yeni bir mahalle belli belirsiz görünüyor.",
    nextQuestRules: { suggests: ["q005"] },
    journey: [{ text: "Yer değiştirdin. Beklenen: {expect.label|text}. Bulunan: {found.label|text}." }],
  },
  {
    ...base,
    id: "q005",
    number: 5,
    slug: "catal",
    title: "Çatal",
    subtitle: "Üç seçenek. Sonra on iki.",
    description: "Sırada ne yapacağına dair iki küçük seçim. Biri kolay. Birinin fazla kapısı var.",
    locationId: "market",
    npcLine: "Haritamdaki her çatal, birinin fazla uzun beklediği bir yerdir.",
    family: "decide",
    dimensions: ["decision-making"],
    difficulty: 1,
    estimatedMinutes: { min: 5, max: 10 },
    contexts: ["home", "work", "outside"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 2 },
    safety: {
      level: "minimal",
      movement: "light",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: ["Her seçenek küçük ve isteğe bağlı. Hiçbiri uymazsa atla.", SAFE.stopAnytime],
    },
    prime: [
      { id: "intro", kind: "narrative", speaker: "cartographer", lines: ["İki menü geliyor. Her birinden gerçekte seçeceğin gibi seç.", "İkincisinden ne seçersen onu yapacaksın."] },
      {
        id: "small",
        kind: "choice",
        role: "decision",
        prompt: "Birini seç.",
        options: [
          { id: "water", label: "Bir bardak suyu yavaşça iç" },
          { id: "window", label: "Pencereden görebildiğin en uzak şeyi bul" },
          { id: "stretch", label: "İki dakika esne" },
        ],
      },
      {
        id: "large",
        kind: "choice",
        role: "decision",
        prompt: "Şimdi bunlardan birini seç.",
        columns: 2,
        options: [
          { id: "surface", label: "Bir yüzeyi tamamen boşalt" },
          { id: "song", label: "Başka hiçbir şey yapmadan bir şarkı dinle" },
          { id: "note", label: "Bir yıl sonraki kendine üç satır yaz" },
          { id: "plant", label: "Bir bitkiye ya da ağaca yakından bak" },
          { id: "shelf", label: "Küçük bir rafı yeniden düzenle" },
          { id: "stairs", label: "Bir kat merdiveni yavaşça çık" },
          { id: "draw", label: "Sana en yakın nesneyi çiz" },
          { id: "breath", label: "Açık bir pencerenin önünde on yavaş nefes" },
          { id: "message", label: "Uzun zamandır yazmadığın birine yaz" },
          { id: "drawer", label: "Bir çekmeceyi düzenle" },
          { id: "page", label: "Rastgele bir kitaptan bir sayfa oku" },
          { id: "sounds", label: "Duyabildiğin her sesi say" },
        ],
      },
    ],
    act: {
      instruction: "Şunu yap: {large.label|phrase}.",
      details: ["Mümkün olmadığı ortaya çıkarsa ilk menüden seçtiğini yap."],
      reminder: "{large.label|text}. Başka hiçbir şey.",
    },
    reflection: [
      { id: "satisfied", kind: "scale", prompt: "Seçtiğinden ne kadar memnunsun?", lowLabel: "Başkasını seçerdim", highLabel: "Tam isabet" },
      {
        id: "lingering",
        kind: "choice",
        role: "reflection",
        prompt: "Yaparken öbür seçenekler aklına geldi mi?",
        options: [
          { id: "no", label: "Hiç" },
          { id: "some", label: "Bir iki kez" },
          { id: "often", label: "Sürekli geri geldiler" },
        ],
      },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "3 seçenekten seçim", ref: "small.latencySec", format: "duration" },
          { label: "12 seçenekten seçim", ref: "large.latencySec", format: "duration" },
        ],
        delta: { label: "Fark", a: "large.latencySec", b: "small.latencySec", format: "signed-duration" },
      },
      {
        kind: "text",
        variants: [
          { when: { compare: { a: "large.latencySec", op: "gt", b: "small.latencySec", ratio: 1.5 } }, text: "Daha çok kapı, eşikte daha uzun bekleyiş. On iki seçenek seni {large.latencySec|duration}, üçü {small.latencySec|duration} tuttu." },
          { text: "On iki seçenekten neredeyse üçten seçtiğin kadar hızlı seçtin. İlk yeterince iyi seçeneği almak gerçek bir stratejidir — ve görüldü." },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "lingering.optionId", op: "eq", value: "often" }, text: "Seçmediğin seçenekler sonrasında da peşini bırakmadı." },
          { when: { ref: "lingering.optionId", op: "eq", value: "no" }, text: "Seçim yapıldıktan sonra öbür seçenekler seni bıraktı." },
          { text: "Öbür seçenekler bir iki kez geri geldi, sonra seni bıraktı." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "choice-overload",
        encounter: [
          { when: { compare: { a: "large.latencySec", op: "gt", b: "small.latencySec", ratio: 1.5 } }, text: "On iki seçenekten seçmek {large.latencySec|duration}, üç seçenekten seçmek {small.latencySec|duration} sürdü." },
          { text: "On iki seçenekten neredeyse üçten seçtiğin kadar hızlı seçtin ({large.latencySec|duration} ve {small.latencySec|duration}) — büyük seçenek kümeleriyle ilişkilendirilen yavaşlama bu kez görülmedi." },
        ],
      },
    ],
    behaviorSignals: ["decision-latency"],
    fragment: "Çarşı'da yalnızca seçenek satan bir tezgâh, malının yarısını kaldırıyor.",
    nextQuestRules: { suggests: ["q006"] },
    journey: [{ text: "On iki seçenekten “{large.label|text}” seçildi, {large.latencySec|duration} içinde." }],
  },
  {
    ...base,
    id: "q006",
    number: 6,
    slug: "ters-sira",
    title: "Ters Sıra",
    subtitle: "Aynı rutin. Farklı sıra.",
    description: "Gününün bir yerinde uykunda bile yapabileceğin bir sıralama var. Onu sök.",
    locationId: "workshop",
    npcLine: "Rutin, tabelaları sökülmüş bir yoldur. Tabelaları geri tak.",
    family: "break",
    dimensions: ["inhibition", "planning"],
    difficulty: 2,
    estimatedMinutes: { min: 5, max: 15 },
    contexts: ["home", "work"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 3 },
    safety: {
      level: "minimal",
      movement: "light",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: ["Sıranın güvenlik için önemli olmadığı bir rutin seç — ısı, bıçak ya da ilaç içermesin.", SAFE.stopAnytime],
    },
    prime: [
      { id: "steps", kind: "list", role: "prime", prompt: "Her gün yaptığın küçük bir rutinin adımlarını sırayla yaz.", hint: "Çay demlemek, çanta hazırlamak, masanı kurmak, evden çıkmaya hazırlanmak.", slots: 5, required: 3, placeholder: "Adım" },
      {
        id: "plan",
        kind: "choice",
        role: "decision",
        prompt: "Onu nasıl bozacaksın?",
        options: [
          { id: "reverse", label: "Mümkün olan yerde adımları tersine çevir" },
          { id: "swap", label: "İki adımın yerini değiştir" },
          { id: "replace", label: "Bir adımı yeni bir şeyle değiştir" },
        ],
      },
    ],
    act: {
      instruction: "Rutini şimdi yap, değiştirilmiş hâliyle: {plan.label|phrase}.",
      details: ["Eski sıraya yine de her başladığında bunu fark et."],
      reminder: "Yeniden düzenlenmiş rutin. Çekimi fark et.",
    },
    recall: [
      { id: "slips", kind: "count", prompt: "Kaç kez yine de eski sırayla başladın?", max: 30 },
      {
        id: "where",
        kind: "choice",
        role: "recall",
        prompt: "Eski sıra en çok nerede çekti?",
        options: [
          { id: "start", label: "Başta" },
          { id: "middle", label: "Ortada" },
          { id: "end", label: "Sona doğru" },
          { id: "none", label: "Hiç çekmedi" },
        ],
      },
    ],
    reflection: [{ id: "slower", kind: "scale", prompt: "Ne kadar yavaştı?", lowLabel: "Yavaş değildi", highLabel: "Çok daha yavaş" }],
    reveal: [
      { kind: "list", ref: "steps", label: "Rutin, yazdığın hâliyle" },
      { kind: "figures", items: [{ label: "Eski sıra kaç kez devraldı", ref: "slips.value", format: "count" }] },
      {
        kind: "text",
        variants: [
          { when: { ref: "slips.value", op: "gte", value: 2 }, text: "Eski sıra {slips.value|count} kez devraldı. Rutin, sırada ne olduğunu senden önce biliyordu." },
          { when: { ref: "slips.value", op: "eq", value: 1 }, text: "Bir kez eski sıra devraldı. Geri kalan zamanda yenisi tuttu." },
          { text: "Yeni sıra tuttu. Yazıya döktüğün adımları yeniden düzenlemek, attığını hiç fark etmediğin adımlardan daha kolaydır." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "capture-error",
        when: { ref: "slips.value", op: "gte", value: 1 },
        encounter: [{ text: "Yeni bir sırayı izlerken eskisine {slips.value|count} kez başladın — alışılmış dizi yeni planı yakaladı." }],
      },
    ],
    behaviorSignals: ["routines-interrupted"],
    completionRules: { interruptsRoutine: true },
    fragment: "Atölye'de bir rutin, parçalara ayrılmış ve etiketlenmiş hâlde tezgâhta duruyor. Biri onu farklı kurmaya niyetli.",
    nextQuestRules: { suggests: ["q007"] },
    journey: [{ text: "{steps.count|count} adımlık bir rutin yeniden düzenlendi. Eski sıra {slips.value|count} kez devraldı." }],
  },
  {
    ...base,
    id: "q007",
    number: 7,
    slug: "haritasiz-sokak",
    title: "Haritasız Sokak",
    subtitle: "Önceden seçilmiş beş dönüş.",
    description: "Bir dönüş dizisini ezberle. Onu yürü. Nereye varacağına şehir karar versin.",
    locationId: "crossroads",
    npcLine: "Bu şehri yüz kez çizdim. Bu beş dönüşün nereye çıktığını hiç çizmedim.",
    family: "explore",
    dimensions: ["recall", "adaptation"],
    difficulty: 3,
    estimatedMinutes: { min: 20, max: 40 },
    contexts: ["outside"],
    energy: "normal",
    people: "solo",
    requiresOutside: true,
    requiresLocation: "Bildiğin, yürünebilir bir mahalle",
    availability: { requiresCampaignProgress: 5 },
    safety: {
      level: "moderate",
      movement: "walking",
      requiresPurchase: false,
      contactsStrangers: false,
      photographsPeople: false,
      sharesLocation: false,
      notes: [
        "Yalnızca güvenli ve kamuya açık yerlerde dön. Bir dönüş mümkün değilse onu atla ve sonraki kavşakta kullan.",
        SAFE.publicKnown,
        "İstediğin an geri dön — görev yine de sayılır.",
        SAFE.eyesUp,
        SAFE.stopAnytime,
      ],
    },
    prime: [
      { id: "intro", kind: "narrative", speaker: "cartographer", lines: ["Sana beş dönüş göstereceğim.", "Onları hatırla. Ekrana bakmadan yürüyeceksin."] },
      {
        id: "turns",
        kind: "sequence-encode",
        mode: "order",
        instruction: "Dönüşleri sırasıyla ezberle.",
        pool: [
          { id: "L", label: "Sol", glyph: { shape: "turn-left", fill: "open", gap: false } },
          { id: "R", label: "Sağ", glyph: { shape: "turn-right", fill: "open", gap: false } },
          { id: "S", label: "Düz", glyph: { shape: "straight", fill: "open", gap: false } },
        ],
        length: 5,
        displayMs: 1400,
      },
    ],
    act: {
      instruction: "Bulunduğun yerden yürü. Her kavşakta sıradaki dönüşü hafızandan al.",
      details: ["Beşi de kullanılınca dur ve etrafına bak: neredesin?", "Dönüşte istediğin yoldan gel."],
      reminder: "Hafızadan beş dönüş. Sonra başını kaldır.",
    },
    recall: [
      { id: "turns-recall", kind: "sequence-recall", source: "turns", mode: "order", prompt: "Sana verilen beş dönüşü sırasıyla yeniden kur." },
      {
        id: "arrived",
        kind: "choice",
        role: "recall",
        prompt: "Dönüşler seni nereye götürdü?",
        options: [
          { id: "new", label: "Hiç gitmediğim bir yere" },
          { id: "rare", label: "Nadiren gittiğim bir yere" },
          { id: "known", label: "Tanıdık bir yere" },
        ],
      },
      { id: "found", kind: "list", role: "recall", prompt: "Orada hatırlamaya değer bir şey var mıydı?", slots: 3, required: 0 },
    ],
    reveal: [
      { kind: "sequence", ref: "turns-recall" },
      {
        kind: "text",
        variants: [
          { when: { ref: "turns-recall.accuracy", op: "eq", value: 1 }, text: "Koca bir yürüyüşten sonra beş dönüşün beşi de, sırasıyla. Dizi şehirden sağ çıktı." },
          { when: { all: [{ ref: "turns-recall.firstCorrect", op: "eq", value: true }, { ref: "turns-recall.middleAccuracy", op: "lt", value: 1 }] }, text: "İlk dönüş keskin kaldı; ortadakiler bulanıklaştı. Başlangıçlar en çok tekrarı alır." },
          { when: { all: [{ ref: "turns-recall.lastCorrect", op: "eq", value: true }, { ref: "turns-recall.middleAccuracy", op: "lt", value: 1 }] }, text: "Son dönüş tuttu; ortadakiler kaydı." },
          { text: "Dizi yolda dağıldı. Şehir, beş şeyi taşımak için gürültülü bir yerdir." },
        ],
      },
      { kind: "list", ref: "found", label: "Dönüşlerin sonunda bulunanlar" },
    ],
    discoveries: [
      {
        discovery: "primacy-effect",
        when: { all: [{ ref: "turns-recall.firstCorrect", op: "eq", value: true }, { ref: "turns-recall.middleAccuracy", op: "lt", value: 1 }] },
        encounter: [{ text: "Yürüyüşten sonra ilk dönüşü hâlâ doğru biliyordun; ortadakilerin bazıları kaymıştı." }],
      },
      {
        discovery: "recency-effect",
        when: { all: [{ ref: "turns-recall.lastCorrect", op: "eq", value: true }, { ref: "turns-recall.middleAccuracy", op: "lt", value: 1 }] },
        encounter: [{ text: "Son dönüş yürüyüşten ortadakilerden daha iyi çıktı." }],
      },
    ],
    behaviorSignals: ["sequence-accuracy"],
    completionRules: { interruptsRoutine: true },
    worldEffects: [{ kind: "open-path", path: "p-unknown" }],
    fragment: "Kavşak'tan kuzeye bir yol uzanıyor ve nehri geçiyor. Ölçüm karşı kıyıda bitiyor.",
    journey: [{ text: "Hafızadan beş dönüş yürüdün. Sonrasında 5 dönüşün {turns-recall.correct|count} tanesini yeniden kurdun." }],
  },
];
