/** Kampanya 2 — GÖZLEMCİ. Dikkat, ayrıntılar, örüntüler. */
import type { Glyph, QuestInput } from "@/domain/content-types";
import { SAFE } from "./safety-notes";

const base = {
  version: 1,
  campaignId: "observer",
  npcId: "watcher",
  requiresPurchase: false as const,
};

const g = (shape: Glyph["shape"], fill: Glyph["fill"] = "open", gap = false): Glyph => ({ shape, fill, gap });

const safetyBase = {
  requiresPurchase: false as const,
  contactsStrangers: false as const,
  photographsPeople: false as const,
  sharesLocation: false as const,
};

export const OBSERVER_QUESTS: QuestInput[] = [
  {
    ...base,
    id: "q008",
    number: 8,
    slug: "gorunmeyen-uc",
    title: "Görünmeyen Üç",
    subtitle: "Yanından geçtiğin ama hiç görmediğin şeyler.",
    description: "Her gün geçtiğin yolda yıllardır orada duran bir şey var. Ona bir kez bile bakmadın.",
    locationId: "observatory",
    npcLine: "Önündekilerin çoğunu görmemeye razı oldun. Bir kısmını geri al.",
    family: "notice",
    dimensions: ["attention", "filtering"],
    difficulty: 1,
    estimatedMinutes: { min: 10, max: 20 },
    contexts: ["outside", "home", "work", "commuting"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    mysteryEligible: true,
    safety: { ...safetyBase, level: "low", movement: "light", notes: [SAFE.eyesUp, SAFE.notDriving, SAFE.stopAnytime] },
    prime: [
      { id: "intro", kind: "narrative", speaker: "watcher", lines: ["Önce gözlerini ısıt."] },
      {
        id: "scan",
        kind: "signal-filter",
        instruction: "Aralıklı olan her halkaya dokun. Bazı halkalar neredeyse aynı.",
        targetLabel: "Aralıklı halka",
        target: { shape: "circle", fill: "open", gap: true },
        lures: [g("circle"), g("circle", "solid")],
        others: [g("square"), g("arch"), g("diamond")],
        rounds: 3,
        cols: 6,
        rows: 4,
        targetsPerRound: [3, 5],
        secondsPerRound: 12,
      },
    ],
    act: {
      instruction: "Daha önce yanından geçtiğin ama hiç bilinçli olarak görmediğin üç şeyi fark et.",
      details: ["Zaten orada olan şeyler olmalı — yeni değil.", "Yukarı bak, aşağı bak, kenarlara bak."],
      reminder: "Hep orada olan üç şey.",
    },
    recall: [
      { id: "unseen", kind: "list", role: "recall", prompt: "Neydiler?", slots: 3, required: 1, placeholder: "ör. bir kapının üstüne kazınmış bir tarih" },
      {
        id: "where",
        kind: "choice",
        role: "recall",
        prompt: "Çoğunlukla neredeydiler?",
        options: [
          { id: "up", label: "Göz hizasının üstünde" },
          { id: "level", label: "Göz hizasında" },
          { id: "down", label: "Göz hizasının altında" },
          { id: "mixed", label: "Her yerde" },
        ],
      },
    ],
    reveal: [
      { kind: "filter", ref: "scan" },
      { kind: "list", ref: "unseen", label: "Bugüne kadar görünmeyenler" },
      {
        kind: "text",
        variants: [
          { when: { ref: "where.optionId", op: "eq", value: "up" }, text: "Bulduklarının çoğu göz hizasının üstündeydi. Bildiği yollarda yukarı bakan pek az insan vardır." },
          { when: { ref: "where.optionId", op: "eq", value: "down" }, text: "Çoğu göz hizasının altındaydı — ayak altında, bir şey takılmadıkça dikkatin gitmediği yerde." },
          { when: { ref: "where.optionId", op: "eq", value: "level" }, text: "Hep göz hizasındaydılar, bakışının tam ortasında saklanıyorlardı." },
          { text: "Bütün görüş alanına yayılmışlardı. Dikkatin boşlukları tek bir yerde değildi." },
        ],
      },
    ],
    discoveries: [
      { discovery: "inattentional-blindness", encounter: [{ text: "Hep göz önünde olan {unseen.count|count} şey, sen onları aramaya çıkana kadar kaydedilmemişti." }] },
    ],
    behaviorSignals: ["attention-misses", "details-recalled"],
    fragment: "Gözlemevi'nin merceği temizlendi. Hâlâ yere bakıyor.",
    nextQuestRules: { suggests: ["q009"] },
    journey: [{ text: "Hep orada olan {unseen.count|count} şey bulundu." }],
  },
  {
    ...base,
    id: "q009",
    number: 9,
    slug: "ikinci-bakis",
    title: "İkinci Bakış",
    subtitle: "Bak. Uzaklaş. Yeniden bak.",
    description: "Arada bir boşlukla iki kez incelenen bir manzara. Sen yokken ne kıpırdadı?",
    locationId: "observatory",
    npcLine: "Hiçbir şey hareketsiz durmaz. Sadece onu hareket ederken yakalayamayız.",
    family: "notice",
    dimensions: ["attention", "recall"],
    difficulty: 2,
    estimatedMinutes: { min: 8, max: 15 },
    contexts: ["home", "work", "outside"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    safety: { ...safetyBase, level: "minimal", movement: "light", notes: ["Her manzara olur: bir pencere, bir masa, güvenle durabileceğin bir sokak köşesi.", SAFE.stopAnytime] },
    prime: [
      { id: "intro", kind: "narrative", speaker: "watcher", lines: ["Önce bu düzeni incele. Onu sonra yeniden göreceksin."] },
      {
        id: "plate",
        kind: "sequence-encode",
        mode: "scene",
        instruction: "Düzeni incele.",
        pool: [
          { id: "a", label: "Boş halka", glyph: g("circle") },
          { id: "b", label: "Dolu halka", glyph: g("circle", "solid") },
          { id: "c", label: "Boş kare", glyph: g("square") },
          { id: "d", label: "Dolu kare", glyph: g("square", "solid") },
          { id: "e", label: "Boş üçgen", glyph: g("triangle") },
          { id: "f", label: "Dolu üçgen", glyph: g("triangle", "solid") },
          { id: "h", label: "Boş kemer", glyph: g("arch") },
          { id: "i", label: "Dolu kemer", glyph: g("arch", "solid") },
          { id: "j", label: "Boş eşkenar dörtgen", glyph: g("diamond") },
          { id: "k", label: "Dolu eşkenar dörtgen", glyph: g("diamond", "solid") },
          { id: "l", label: "Çubuk", glyph: g("bar", "solid") },
        ],
        length: 7,
        displayMs: 9000,
        grid: { cols: 4, rows: 3 },
      },
      { id: "brief", kind: "narrative", speaker: "watcher", lines: ["Şimdi gerçeği. Bir manzara seç — bir pencere, bir sokak, bir masa.", "Bir dakika incele. Sonra beş dakikalığına bırak."] },
    ],
    act: {
      instruction: "Gerçek bir manzarayı bir dakika incele. Beş dakika uzaklaş. Geri gel ve yeniden bak.",
      details: ["Uzaktayken bambaşka bir şey yap.", "Döndüğünde: ne değişti?"],
      reminder: "Bir dakika bak. Beş dakika uzak dur. Sonra ikinci bakış.",
    },
    recall: [
      { id: "plate-change", kind: "sequence-recall", source: "plate", mode: "scene-change", changes: 1, prompt: "Az önceki düzen. Bir işaret farklı. Hangisi?" },
      { id: "changes", kind: "count", prompt: "Gerçek manzarada kaç değişiklik fark ettin?", max: 30 },
      { id: "what", kind: "list", role: "recall", prompt: "Ne değişti?", slots: 4, required: 0 },
    ],
    reveal: [
      { kind: "scene", ref: "plate-change" },
      {
        kind: "text",
        variants: [
          { when: { ref: "plate-change.detected", op: "eq", value: true }, text: "Arada olan her şeye rağmen değişen işareti buldun." },
          { text: "Değişen işaret gözünden kaçtı. Yedi işaretten biriydi ve arada bir yürüyüş vardı." },
        ],
      },
      { kind: "list", ref: "what", label: "Gerçek manzarada değişenler" },
    ],
    discoveries: [
      {
        discovery: "change-blindness",
        encounter: [
          { when: { ref: "plate-change.detected", op: "eq", value: true }, text: "Uzun bir kesintiden sonra değişen işareti yakaladın. Çoğu insan başka yere bakarken olan değişiklikleri kaçırır." },
          { text: "Sen yokken bir işaret değişti ve gözden kaçtı — bir kesintinin gizlediği küçük, temiz bir değişiklik." },
        ],
      },
    ],
    behaviorSignals: ["change-detection"],
    fragment: "Biri Gözlemevi'ndeki teleskoplardan birinin yerini değiştirmiş. Neredeyse kimse fark etmedi.",
    nextQuestRules: { suggests: ["q010"] },
    journey: [
      { when: { ref: "plate-change.detected", op: "eq", value: true }, text: "İkinci bakış: değişen işaret yakalandı; gerçek manzarada {changes.value|count} değişiklik." },
      { text: "İkinci bakış: değişen işaret kaçtı; gerçek manzarada {changes.value|count} değişiklik." },
    ],
  },
  {
    ...base,
    id: "q010",
    number: 10,
    slug: "tek-kural",
    title: "Tek Kural",
    subtitle: "Yalnızca tek bir türü fark et.",
    description: "Bir kural seç. On dakika boyunca dünyada ondan başka bir şey yok.",
    locationId: "garden",
    npcLine: "Dikkat bir fenerdir, projektör değil. Doğrult onu.",
    family: "notice",
    dimensions: ["attention", "filtering"],
    difficulty: 1,
    estimatedMinutes: { min: 10, max: 15 },
    contexts: ["outside", "home", "work", "commuting"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    mysteryEligible: true,
    safety: { ...safetyBase, level: "low", movement: "light", notes: [SAFE.eyesUp, SAFE.notDriving, SAFE.stopAnytime] },
    prime: [
      {
        id: "rule",
        kind: "signal-filter",
        instruction: "Yalnızca dolu kareler sayılır. Gerisini boş ver.",
        targetLabel: "Dolu kare",
        target: { shape: "square", fill: "solid" },
        lures: [g("square"), g("diamond", "solid")],
        others: [g("circle", "solid"), g("triangle"), g("arch", "solid")],
        rounds: 2,
        cols: 5,
        rows: 4,
        targetsPerRound: [3, 5],
        secondsPerRound: 10,
      },
      {
        id: "pick",
        kind: "choice",
        role: "decision",
        prompt: "Gerçek dünya için kuralını seç.",
        options: [
          { id: "round", label: "Yalnızca yuvarlak şeyler" },
          { id: "red", label: "Yalnızca kırmızı şeyler" },
          { id: "words", label: "Yalnızca yazılı kelimeler" },
          { id: "mechanical", label: "Yalnızca mekanik sesler" },
          { id: "green", label: "Yalnızca canlı yeşil şeyler" },
        ],
      },
    ],
    act: {
      instruction: "On dakika boyunca yalnızca bunu fark et: {pick.label|phrase}. Onları say.",
      details: ["Elinden geldiğince geri kalan her şeyi yok say.", "Kabaca bir sayı yeterli."],
      reminder: "{pick.label|text}. Başka hiçbir şey.",
    },
    recall: [
      { id: "matches", kind: "count", prompt: "Kaç tane saydın?", max: 300 },
      {
        id: "aside",
        kind: "choice",
        role: "recall",
        prompt: "Tahmin etmeden: kuralına uymayan en dikkat çekici şey neydi?",
        options: [
          { id: "clear", label: "Açıkça söyleyebilirim" },
          { id: "vague", label: "Belli belirsiz bir fikrim var" },
          { id: "none", label: "Dürüst olmak gerekirse bilmiyorum" },
        ],
      },
    ],
    reflection: [{ id: "narrow", kind: "scale", prompt: "Dünya ne kadar daraldı?", lowLabel: "Hiç", highLabel: "Bir tünel gibi" }],
    reveal: [
      { kind: "filter", ref: "rule" },
      { kind: "figures", items: [{ label: "Sayılan eşleşme", ref: "matches.value", format: "count" }] },
      {
        kind: "text",
        variants: [
          { when: { ref: "aside.optionId", op: "eq", value: "none" }, text: "{matches.value|count} eşleşme — ve başka neyin olduğunu söyleyemiyorsun. Fener işte böyle çalışır." },
          { when: { ref: "aside.optionId", op: "eq", value: "vague" }, text: "{matches.value|count} eşleşme. Geri kalan her şey belli belirsiz bir izlenim — görülmüş, saklanmamış." },
          { text: "{matches.value|count} eşleşme ve yine de kuralın dışında bir şeyi aklında tuttun. Fener biraz sızdırıyor." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "selective-attention",
        encounter: [
          { when: { ref: "aside.optionId", op: "ne", value: "clear" }, text: "“{pick.label|text}” kuralını izlemek sana {matches.value|count} eşleşme getirdi — ve sahnenin geri kalanını hatırlamayı zorlaştırdı." },
          { text: "Kuralı tuttun ve yine de dışında bir şey fark ettin. Seçici dikkat görüşü daraltır ama nadiren tamamen kapatır." },
        ],
      },
    ],
    behaviorSignals: ["attention-misses"],
    fragment: "Bahçe'de tek bir çiçek türü etiketlenmiş. Geri kalanlar aldırmadan büyüyor.",
    nextQuestRules: { suggests: ["q011"] },
    journey: [{ text: "{pick.label|text}: {matches.value|count} sayıldı." }],
  },
  {
    ...base,
    id: "q011",
    number: 11,
    slug: "dinleme-kulesi",
    title: "Dinleme Kulesi",
    subtitle: "Sonra sorulacakmış gibi dinle.",
    description: "Zaten yapacağın bir sohbet. Bu sefer bir parçan not alıyor — hiçbir şey yazmadan.",
    locationId: "archive",
    npcLine: "İnsanlar demek istediklerinden fazlasını söyler. Çoğu duyulmadan kalır.",
    family: "connect",
    dimensions: ["attention", "recall", "estimation"],
    difficulty: 2,
    estimatedMinutes: { min: 10, max: 30 },
    contexts: ["with-people", "home", "work"],
    energy: "normal",
    people: "required",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 1 },
    safety: {
      ...safetyBase,
      level: "low",
      movement: "none",
      notes: ["Yalnızca zaten tanıdığın biriyle, zaten yapacağın bir sohbette.", "Hiçbir şey kaydetme. Senden yalnızca sayılar istenecek — kimin ne söylediği asla.", SAFE.stopAnytime],
    },
    prime: [{ id: "questions", kind: "estimate", prompt: "Sana kaç soru soracaklarını düşünüyorsun?", unit: "count", min: 0, max: 30, step: 1, initial: 5 }],
    act: {
      instruction: "Sıradan bir sohbet et. Üç tür ayrıntıya kulak ver: bir isim, bir sayı ve bir yer.",
      details: ["Not alma. Sohbeti yönlendirme.", "Sana kaç soru sorduklarını sessizce say."],
      reminder: "Bir isim, bir sayı, bir yer. Sorularını say.",
    },
    recall: [
      { id: "questions-actual", kind: "actual", prompt: "Gerçekte kaç soru sordular?", unit: "count", source: "manual", pairsWith: "questions", max: 60 },
      {
        id: "details",
        kind: "choice",
        role: "recall",
        prompt: "Üç ayrıntıdan kaçını hâlâ hatırlıyorsun?",
        options: [
          { id: "d0", label: "Hiçbirini" },
          { id: "d1", label: "Birini" },
          { id: "d2", label: "İkisini" },
          { id: "d3", label: "Üçünü de" },
        ],
      },
      {
        id: "part",
        kind: "choice",
        role: "recall",
        prompt: "Sohbetin en iyi hangi kısmını hatırlıyorsun?",
        options: [
          { id: "beginning", label: "Başını" },
          { id: "middle", label: "Ortasını" },
          { id: "end", label: "Sonunu" },
          { id: "even", label: "Hepsini aşağı yukarı aynı" },
        ],
      },
    ],
    reflection: [{ id: "different", kind: "scale", prompt: "Bu şekilde dinlemek ne kadar farklı hissettirdi?", lowLabel: "Hiç farklı değil", highLabel: "Çok farklı" }],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Tahminin", ref: "questions.value", format: "count" },
          { label: "Sordukları", ref: "questions-actual.value", format: "count" },
        ],
        delta: { label: "Fark", a: "questions-actual.value", b: "questions.value", format: "signed-count" },
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "part.optionId", op: "eq", value: "end" }, text: "Sohbetin sonu şimdi en net olanı. Bu avantaj önümüzdeki birkaç saatte genellikle söner." },
          { when: { ref: "part.optionId", op: "eq", value: "beginning" }, text: "Akılda kalan başlangıç oldu. Açılış konuşmaları en çok tekrarı alır." },
          { when: { ref: "part.optionId", op: "eq", value: "middle" }, text: "Ortası seninle kaldı — daha az rastlanan bir durum; muhtemelen sohbetin en önemli olduğu yer orasıydı." },
          { text: "Sohbetin tamamı boyunca eşit kaldı." },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "details.optionId", op: "eq", value: "d3" }, text: "Üç ayrıntının üçü de hâlâ seninle." },
          { when: { ref: "details.optionId", op: "eq", value: "d0" }, text: "Üç ayrıntının hiçbiri geri gelmedi. Dinlemek ile saklamak ayrı işlerdir." },
          { text: "Bazı ayrıntılar geri geldi; bazıları duyuldu ve bırakıldı." },
        ],
      },
    ],
    discoveries: [
      { discovery: "recency-effect", when: { ref: "part.optionId", op: "eq", value: "end" }, encounter: [{ text: "Sohbetin hemen ardından en iyi hatırladığın, sonu." }] },
      { discovery: "primacy-effect", when: { ref: "part.optionId", op: "eq", value: "beginning" }, encounter: [{ text: "Sohbetin açılışı, sonrasındaki her şeyden daha çok seninle kaldı." }] },
    ],
    behaviorSignals: ["prediction-error"],
    fragment: "Arşiv'de yeni bir raf sohbetleri tutuyor — yalnızca ana hatlarını, asla sözcükleri değil.",
    nextQuestRules: { suggests: ["q012"] },
    journey: [{ text: "Dikkatle dinledin. {questions.value|count} soru tahmin ettin; {questions-actual.value|count} soru sordular." }],
  },
  {
    ...base,
    id: "q012",
    number: 12,
    slug: "ses-haritasi",
    title: "Ses Haritası",
    subtitle: "Bulunduğun yeri kulakla haritala.",
    description: "Beş dakika hareketsiz dur. Her sesin bir yönü var.",
    locationId: "garden",
    npcLine: "Duymayı bıraktığın sesler hâlâ geliyor.",
    family: "notice",
    dimensions: ["attention", "estimation"],
    difficulty: 1,
    estimatedMinutes: { min: 5, max: 10 },
    contexts: ["outside", "home", "work"],
    energy: "low",
    people: "solo",
    requiresOutside: false,
    mysteryEligible: true,
    availability: { requiresCampaignProgress: 2 },
    safety: { ...safetyBase, level: "minimal", movement: "none", notes: ["Gözlerini yalnızca bunu yapmanın güvenli olduğu bir yerdeysen kapat.", SAFE.stopAnytime] },
    prime: [{ id: "guess", kind: "estimate", prompt: "Beş dakikada kaç farklı ses duyacağını düşünüyorsun?", unit: "count", min: 0, max: 40, step: 1, initial: 6 }],
    act: {
      instruction: "Beş dakika hareketsiz dur ve her farklı sesi say.",
      details: ["Her birinin kabaca hangi yönden geldiğini fark et.", "Gözlerin açık ya da bulunduğun yer güvenliyse kapalı."],
      reminder: "Beş dakika. Her ses. Her yön.",
    },
    recall: [
      { id: "heard", kind: "actual", prompt: "Kaç farklı ses duydun?", unit: "count", source: "manual", pairsWith: "guess", max: 80 },
      {
        id: "constant",
        kind: "choice",
        role: "recall",
        prompt: "Baştan beri orada olan ama ancak bir süre sonra fark ettiğin bir ses var mıydı?",
        options: [
          { id: "yes", label: "Evet" },
          { id: "unsure", label: "Emin değilim" },
          { id: "no", label: "Hayır" },
        ],
      },
      { id: "sounds", kind: "list", role: "recall", prompt: "Hatırladıklarını yaz.", slots: 6, required: 0, placeholder: "ör. bir buzdolabı, solda" },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Beklediğin", ref: "guess.value", format: "count" },
          { label: "Duyduğun", ref: "heard.value", format: "count" },
        ],
        delta: { label: "Fark", a: "heard.value", b: "guess.value", format: "signed-count" },
      },
      {
        kind: "text",
        variants: [
          { when: { compare: { a: "heard.value", op: "gt", b: "guess.value" } }, text: "Beklediğinden fazla ses. Burası zihnindeki resminden daha gürültülüymüş." },
          { when: { compare: { a: "heard.value", op: "lt", b: "guess.value" } }, text: "Beklediğinden az ses. Bazı yerler ünlerinden daha sessizdir." },
          { text: "Tam beklediğin sayı." },
        ],
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "constant.optionId", op: "eq", value: "yes" }, text: "Bir ses baştan beri oradaydı. Sen yalnızca onu almayı bırakmıştın." },
          { text: "Bu sefer gizli bir uğultu yoktu — ya da yüzeye çıkmadı." },
        ],
      },
      { kind: "list", ref: "sounds", label: "Ses haritan" },
    ],
    discoveries: [
      {
        discovery: "habituation",
        when: { ref: "constant.optionId", op: "eq", value: "yes" },
        encounter: [{ text: "Baştan beri orada olan bir ses ancak bir süre sonra yüzeye çıktı — kulağın onu arka plan olarak dosyalamıştı." }],
      },
    ],
    behaviorSignals: ["prediction-error"],
    fragment: "Bahçe eskisinden daha sessiz. Ya da sen daha fazlasını duyabiliyorsun.",
    nextQuestRules: { suggests: ["q013"] },
    journey: [{ text: "{heard.value|count} ses duyuldu; {guess.value|count} bekleniyordu." }],
  },
  {
    ...base,
    id: "q013",
    number: 13,
    slug: "hipotez",
    title: "Hipotez",
    subtitle: "Bir örüntü tahmin et. Onu çürütmeye çalış.",
    description: "Çevren hakkında bir iddiada bulun. Sonra yanıldığının kanıtını aramaya çık.",
    locationId: "crossroads",
    npcLine: "Kanıt bulmak kolaydır. Asıl ustalık, öbür türünü aramaktır.",
    family: "predict",
    dimensions: ["attention", "decision-making", "estimation"],
    difficulty: 2,
    estimatedMinutes: { min: 10, max: 15 },
    contexts: ["outside", "home", "work", "commuting"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 3 },
    safety: { ...safetyBase, level: "low", movement: "light", notes: ["Nesneleri ve yerleri kontrol et — asla insanları değil.", SAFE.eyesUp, SAFE.notDriving, SAFE.stopAnytime] },
    prime: [
      {
        id: "claim",
        kind: "choice",
        role: "decision",
        prompt: "Sınamak için bir iddia seç.",
        options: [
          { id: "doors", label: "Önünden geçtiğim kapıların çoğu koyu renkli" },
          { id: "sills", label: "Pencerelerin çoğunun pervazında bir şey var" },
          { id: "vehicles", label: "Park etmiş araçların çoğu açık renkli" },
          { id: "capitals", label: "Tabelaların çoğunda büyük harf kullanılmış" },
          { id: "plants", label: "Pencerelerin ya da balkonların çoğunda bitki var" },
        ],
      },
      { id: "expect", kind: "estimate", prompt: "Kontrol edeceğin sonraki on örnekten kaçı iddiaya uyacak?", unit: "count", min: 0, max: 10, step: 1, initial: 7 },
    ],
    act: {
      instruction: "Bu iddianın on örneğini kontrol et: {claim.label|phrase}.",
      details: ["Dürüstçe say — uysun uymasın her örneği.", "Seni haksız çıkaracak olanları arayıp bulmaya çalış."],
      reminder: "On örnek. Uymayanları da say.",
    },
    recall: [
      { id: "fit", kind: "actual", prompt: "Onun kaçı iddiaya uydu?", unit: "count", source: "manual", pairsWith: "expect", max: 10 },
      {
        id: "search",
        kind: "choice",
        role: "reflection",
        prompt: "Dürüstçe: hangi örnekleri kontrol edeceğini nasıl seçtin?",
        options: [
          { id: "fit", label: "Uyanlara doğru kaydım" },
          { id: "any", label: "Karşıma çıktıkları sırayla aldım" },
          { id: "against", label: "Uymayacak olanları aradım" },
        ],
      },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Beklediğin", ref: "expect.value", format: "count" },
          { label: "İddiaya uyan", ref: "fit.value", format: "count" },
        ],
        delta: { label: "Fark", a: "fit.value", b: "expect.value", format: "signed-count" },
      },
      {
        kind: "text",
        variants: [
          { when: { ref: "search.optionId", op: "eq", value: "fit" }, text: "Uyan örneklere doğru kaydığını fark ettin. Çoğu insan bu çekimi hisseder; azı fark eder." },
          { when: { ref: "search.optionId", op: "eq", value: "against" }, text: "Karşı örnekleri aradın. Göründüğünden daha nadirdir." },
          { text: "Örnekleri karşına çıktıkları gibi aldın — bir sokağın izin verdiği en adil sınama." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "confirmation-bias",
        encounter: [
          { when: { ref: "search.optionId", op: "eq", value: "fit" }, text: "Bir iddiayı sınaman istendiğinde, onu destekleyen örneklere doğru kaydın." },
          { when: { ref: "search.optionId", op: "eq", value: "against" }, text: "İddianı çürütecek örnekleri bilerek aradın — olağan çekim ters yöne işler." },
          { text: "İddianı karşına ne çıkarsa onunla sınadın: beklediğin {expect.value|count} yerine 10 örnekten {fit.value|count} tanesi uydu." },
        ],
      },
    ],
    behaviorSignals: ["prediction-error"],
    fragment: "Kavşak'ta biri kaldırıma tebeşirle bir iddia yazmış, altına da istisnaların çetelesini.",
    nextQuestRules: { suggests: ["q014"] },
    journey: [{ text: "“{claim.label|text}” sınandı: 10 örnekten {fit.value|count} tanesi uydu." }],
  },
  {
    ...base,
    id: "q014",
    number: 14,
    slug: "yukari-bak",
    title: "Yukarı Bak",
    subtitle: "Göz hizasının üstündeki şehir.",
    description: "Şehrin çoğu insanın gözünü hiç kaldırmadığı koca bir katmanı var. On dakikanı orada geçir.",
    locationId: "observatory",
    npcLine: "Gözlemevi yukarı bakmak için yapıldı. Ziyaretçilerin çok azı bakar.",
    family: "notice",
    dimensions: ["attention", "estimation"],
    difficulty: 2,
    estimatedMinutes: { min: 10, max: 20 },
    contexts: ["outside", "home", "work"],
    energy: "normal",
    people: "solo",
    requiresOutside: false,
    availability: { requiresCampaignProgress: 5 },
    safety: {
      ...safetyBase,
      level: "low",
      movement: "light",
      notes: ["Her yukarı baktığında yürümeyi bırak. Karşıdan karşıya geçerken asla yukarı bakma.", SAFE.publicKnown, SAFE.stopAnytime],
    },
    prime: [
      {
        id: "high",
        kind: "signal-filter",
        instruction: "Yalnızca boş kemerlere dokun.",
        targetLabel: "Boş kemer",
        target: { shape: "arch", fill: "open" },
        lures: [g("arch", "solid"), g("circle", "open", true)],
        others: [g("square"), g("triangle", "solid"), g("bar", "solid")],
        rounds: 2,
        cols: 6,
        rows: 4,
        targetsPerRound: [3, 6],
        secondsPerRound: 10,
      },
      { id: "expect", kind: "estimate", prompt: "On dakikada göz hizasının üstünde kaç şey fark edeceksin?", unit: "count", min: 0, max: 60, step: 1, initial: 8 },
    ],
    act: {
      instruction: "On dakika boyunca yalnızca göz hizasının üstüne bak.",
      details: ["Çatı hatları, tavanlar, teller, üst pencereler, ağaç tepeleri, şeylerin altları.", "Kabaca bir sayı tut. Her yukarı baktığında dur."],
      reminder: "Göz hizasının üstü. On dakika. Bakmak için dur.",
    },
    recall: [
      { id: "found", kind: "actual", prompt: "Kaç tane fark ettin?", unit: "count", source: "manual", pairsWith: "expect", max: 300 },
      { id: "best", kind: "list", role: "recall", prompt: "Hangi üçünü yeniden arayacaksın?", slots: 3, required: 1 },
      {
        id: "new",
        kind: "choice",
        role: "recall",
        prompt: "Bunlardan herhangi birini daha önce fark etmiş miydin?",
        options: [
          { id: "none", label: "Hiçbirini" },
          { id: "some", label: "Bazılarını" },
          { id: "most", label: "Çoğunu" },
        ],
      },
    ],
    reveal: [
      {
        kind: "figures",
        items: [
          { label: "Beklediğin", ref: "expect.value", format: "count" },
          { label: "Fark ettiğin", ref: "found.value", format: "count" },
        ],
        delta: { label: "Fark", a: "found.value", b: "expect.value", format: "signed-count" },
      },
      { kind: "list", ref: "best", label: "Yeniden yukarı bakmaya değer" },
      {
        kind: "text",
        variants: [
          { when: { ref: "new.optionId", op: "eq", value: "none" }, text: "Hiçbiri daha önce kaydedilmemişti. Şehrin koca bir katmanı, baştan beri göz önündeymiş." },
          { when: { ref: "new.optionId", op: "eq", value: "some" }, text: "Bazılarını görmüştün. Çoğu, bakış hizanın hemen üstünde bekliyordu." },
          { text: "Çoğunu daha önce görmüştün. Ya yukarı bakan birisin — ya da alçak bir yerde yaşıyorsun." },
        ],
      },
    ],
    discoveries: [
      {
        discovery: "inattentional-blindness",
        when: { ref: "new.optionId", op: "ne", value: "most" },
        encounter: [{ text: "Göz hizasının üstünde {found.value|count} şey saydın — çoğu, baştan beri görüş alanında olmasına rağmen daha önce hiç fark edilmemişti." }],
      },
    ],
    behaviorSignals: ["prediction-error", "details-recalled"],
    fragment: "Gözlemevi'nin kubbesi yıllar sonra ilk kez açılıyor.",
    journey: [{ text: "{act.durationMin|min} boyunca yukarı baktın. {expect.value|count} beklenirken {found.value|count} şey fark edildi." }],
  },
];
